# This file only contains values that should be different in a dev environment

pingaccess-admin:
  envs:
    SERVER_PROFILE_ADMIN_BRANCH: "${SERVER_PROFILE_BRANCH}"
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

pingaccess-engine:
  envs:
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"


pingfederate-admin:
  envs:
    SERVER_PROFILE_ADMIN_BRANCH: "${SERVER_PROFILE_BRANCH}"
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

pingfederate-engine:
  envs:
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

pingdirectory:
  envs:
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

pingdataconsole:
  envs:
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"

pingauthorize:
  enabled: true
  envs:
    SERVER_PROFILE_BRANCH: "${SERVER_PROFILE_BRANCH}"